#!/bin/bash
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Reload systemd after removing service files
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
        fi
        ;;
        
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac



exit 0

