name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/cuemsengine/${{ github.event.release.name }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true

      - name: Build
        run: poetry install --without dev && poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
